name: iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - iOS
          - mac-catalyst
    steps:
      - uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          working-directory: ./
          
      - name: Record UITest Videos
        run: |
          xcodebuild -destination 'platform=iOS Simulator,name=iPhone 14' \
           -project DataCollector.xcodeproj \
           -scheme DataCollectorUITests \
           -parallel-testing-enabled NO \
           test | .github/workflows/xcuitestrecorder "iPhone 14" docs/UITestVideos

