
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Xcode build for ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [macOS, "iOS Simulator"]


    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Deps
        run: .github/tools/installdeps


      - name: Test
        env:
          scheme: ${{ 'default' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          filetype_parameter="project"
          file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=${{ matrix.platform }},name=$device"

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()