
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Xcode build for ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [macOS, iOS]


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Deps
        run: .github/tools/installdeps


      - name: ${{ matrix.platform }} Tests
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: DataCollector.xcodeproj
          scheme: DataCollectorTests
          destination: platform=${{ matrix.platform }}
          action: test
