
name: Build@Mac

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Xcode build for ${{ matrix.platform }}
    runs-on: macos-latest
    env:
      scheme: DataCollectorTests
      filetype_parameter: project
      file_to_build: DataCollector.xcodeproj

    strategy:
      fail-fast: false
      matrix:
        platform: [macOS, "iOS Simulator"]


    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Deps
        run: .github/tools/installdeps

      - name: Test
        run: |
          if [ "${{ matrix.platform }}" == "macOS" ]; then 
            deviceNameParam=""
          else
            device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
            deviceNameParam=",name=$device"
          fi
          xcodebuild test -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=${{ matrix.platform }}$deviceNameParam" -resultBundlePath TestResults | xcpretty

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()